#!/bin/bash
#!/bin/bash
sudo apt-get install virtualbox-source -y
sudo apt-get install virtualbox-guest-utils -y
sudo apt-get install virtualbox-guest-additions-iso -y
sudo apt-get install virtualbox-guest-dkms -y
sudo apt-get install virtualbox-dkms -y
sudo apt-get install virtualbox-guest-dkms-hwe -y
sudo apt-get install virtualbox-ext-pack -y
sudo apt-get install virtualbox -y
sudo apt-get install virtualbox-guest-x11-hwe -y
sudo apt-get install virtualbox-guest-source -y
sudo apt-get install virtualbox-qt -y
sudo apt-get install virtualbox-guest-source-hwe -y
sudo apt-get install virtualbox-guest-utils-hwe -y
sudo apt-get install virtualbox-6.1 -y
sudo apt-get install virtualbox-guest-x11 -y
sudo apt-get install virtualbox-source -y
sudo apt-get install virtualbox-guest-utils -y
sudo apt-get install virtualbox-guest-additions-iso -y
sudo apt-get install virtualbox-guest-dkms -y
sudo apt-get install virtualbox-dkms -y
sudo apt-get install virtualbox-guest-dkms-hwe -y
sudo apt-get install virtualbox-ext-pack -y
sudo apt-get install virtualbox -y
sudo apt-get install virtualbox-guest-x11-hwe -y
sudo apt-get install virtualbox-guest-source -y
sudo apt-get install virtualbox-qt -y
sudo apt-get install virtualbox-guest-source-hwe -y
sudo apt-get install virtualbox-guest-utils-hwe -y
sudo apt-get install virtualbox-6.1 -y
sudo apt-get install virtualbox-guest-x11 -y
sudo apt-get install virtualbox-source -y
sudo apt-get install virtualbox-guest-utils -y
sudo apt-get install virtualbox-guest-additions-iso -y
sudo apt-get install virtualbox-guest-dkms -y
sudo apt-get install virtualbox-dkms -y
sudo apt-get install virtualbox-guest-dkms-hwe -y
sudo apt-get install virtualbox-ext-pack -y
sudo apt-get install virtualbox -y
sudo apt-get install virtualbox-guest-x11-hwe -y
sudo apt-get install virtualbox-guest-source -y
sudo apt-get install virtualbox-qt -y
sudo apt-get install virtualbox-guest-source-hwe -y
sudo apt-get install virtualbox-guest-utils-hwe -y
sudo apt-get install virtualbox-6.1 -y
sudo apt-get install virtualbox-guest-x11 -y
